#!/usr/bin/env node

/**
 * Shelly v2.0 - The AI-Powered Intent CLI
 *
 * Features:
 * - Natural Language Processing (NLP)
 * - Advanced Typo Tolerance (Levenshtein Distance)
 * - Pattern Recognition
 * - Context-Aware Execution
 * - File Creation & Management
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

// Colors for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m',
};

const log = {
  info: (msg) => console.log(`${colors.cyan}${colors.bright}ℹ️${colors.reset} ${msg}`),
  success: (msg) => console.log(`${colors.green}${colors.bright}✅${colors.reset} ${msg}`),
  warn: (msg) => console.log(`${colors.yellow}${colors.bright}⚠️${colors.reset} ${msg}`),
  error: (msg) => console.log(`${colors.red}${colors.bright}❌${colors.reset} ${msg}`),
  ai: (msg) => console.log(`${colors.blue}${colors.bright}🤖${colors.reset} ${msg}`),
};

// --- Configuration ---
const TYPO_THRESHOLD = 2;
const WORKSPACE_DIR = process.cwd();

// --- The Brain: Intent Mapping & Keywords ---
const INTENT_MAP = [
  {
    intent: 'create',
    keywords: ['create', 'make', 'new', 'generate', 'write', 'add', 'touch', 'build', 'folder', 'directory'],
    patterns: [/named\s+([^\s]+)/i, /called\s+([^\s]+)/i, /file\s+([^\s\.]+\.[^\s]+)/i],
    description: 'Creates files or folders (e.g., "create a file named blah.js")',
    action: async (args) => {
      const fullInput = args.join(' ');
      let fileName = null;
      let isFolder = fullInput.includes('folder') || fullInput.includes('directory') || fullInput.includes('dir');

      const namePatterns = [
        /named\s+([^\s]+)/i,
        /called\s+([^\s]+)/i,
        /file\s+([^\s\.]+\.[^\s]+)/i,
        /make\s+([^\s]+)/i,
        /create\s+([^\s]+)/i
      ];

      for (const pattern of namePatterns) {
        const match = fullInput.match(pattern);
        if (match) {
          fileName = match[1];
          break;
        }
      }

      if (!fileName) {
        log.error('I couldn\'t figure out what name to use. Try: "create a file named hello.js"');
        return;
      }

      fileName = fileName.split(' ')[0];
      const targetPath = path.join(WORKSPACE_DIR, fileName);

      try {
        if (isFolder) {
          fs.mkdirSync(targetPath, { recursive: true });
          log.success(`Folder created: ${fileName}`);
        } else {
          let content = '';
          if (fileName.endsWith('.js') || fileName.endsWith('.ts')) {
            content = `// Generated by Shelly\nconsole.log('Hello from ${fileName}');\n`;
          } else if (fileName.endsWith('.json')) {
            content = '{}\n';
          } else if (fileName.endsWith('.md')) {
            content = `# ${fileName.replace('.md', '')}\n\nGenerated by Shelly.\n`;
          }
          fs.writeFileSync(targetPath, content);
          log.success(`File created: ${fileName}`);
        }
      } catch (err) {
        log.error(`Error creating file: ${err.message}`);
      }
    }
  },
  {
    intent: 'start',
    keywords: ['start', 'run', 'launch', 'boot', 'begin', 'go', 'execute', 'open'],
    description: 'Detects project, installs dependencies, and runs the app',
    action: async (args) => {
      log.ai('Scanning for project type...');
      const projectType = detectProjectType();
      if (!projectType) {
        log.error('No supported project found (looking for package.json, bun.lockb, etc.)');
        return;
      }
      log.success(`Found ${projectType.type} project!`);

      log.info('Installing dependencies...');
      await runCommand(projectType.manager, ['install']);

      const script = args.find(a => ['dev', 'start', 'build', 'test'].includes(a)) || detectDefaultScript(projectType);
      log.info(`Running script: ${script}...`);
      await runCommand(projectType.manager, ['run', script]);
    }
  },
  {
    intent: 'test',
    keywords: ['test', 'check', 'verify', 'spec', 'jest', 'mocha', 'tset', 'tests', 'testing'],
    description: 'Runs the test suite',
    action: async () => {
      log.ai('Running tests...');
      const projectType = detectProjectType();
      if (!projectType) return log.error('No project found.');

      const testCommands = ['test', 'spec', 'check'];
      let ran = false;
      for (const cmd of testCommands) {
        if (hasScript(projectType, cmd)) {
          await runCommand(projectType.manager, ['run', cmd]);
          ran = true;
          break;
        }
      }
      if (!ran) log.warn('No test script found in package.json');
    }
  },
  {
    intent: 'clean',
    keywords: ['clean', 'clear', 'purge', 'remove', 'delete', 'rm', 'clr', 'trash'],
    description: 'Cleans node_modules and build artifacts',
    action: async () => {
      log.ai('Cleaning up project...');
      const dirsToDelete = ['node_modules', 'dist', 'build', '.next', 'coverage', 'tmp'];
      let deletedCount = 0;

      dirsToDelete.forEach(dir => {
        const dirPath = path.join(WORKSPACE_DIR, dir);
        if (fs.existsSync(dirPath)) {
          fs.rmSync(dirPath, { recursive: true, force: true });
          log.info(`Deleted ${dir}`);
          deletedCount++;
        }
      });

      if (deletedCount === 0) {
        log.info('Nothing to clean!');
      } else {
        log.success(`All clean! Deleted ${deletedCount} directories.`);
      }
    }
  },
  {
    intent: 'doctor',
    keywords: ['doctor', 'fix', 'heal', 'repair', 'broken', 'help', 'why', 'diagnose', 'debug'],
    description: 'Diagnoses common project issues',
    action: async () => {
      log.ai('Dr. Shelly is examining your project...');
      const issues = [];

      if (!fs.existsSync(path.join(WORKSPACE_DIR, 'package.json'))) {
        issues.push('❌ Missing package.json');
      } else {
        issues.push('✅ package.json found');
      }

      if (!fs.existsSync(path.join(WORKSPACE_DIR, 'node_modules'))) {
        issues.push('⚠️ node_modules missing (run "shelly install")');
      } else {
        issues.push('✅ node_modules found');
      }

      const nodeVersion = process.version;
      issues.push(`ℹ️ Node version: ${nodeVersion}`);

      log.info('Diagnosis Report:');
      issues.forEach(i => console.log(`   ${i}`));

      if (issues.some(i => i.startsWith('❌') || i.startsWith('⚠️'))) {
        log.info('Recommendation: Run "shelly start" to auto-fix environment.');
      } else {
        log.success('Your project looks healthy!');
      }
    }
  },
  {
    intent: 'scan',
    keywords: ['scan', 'analyze', 'inspect', 'look', 'see', 'find', 'list', 'show'],
    description: 'Scans project structure and dependencies',
    action: async () => {
      log.ai('Scanning project structure...');
      const files = fs.readdirSync(WORKSPACE_DIR);
      log.info(`Found ${files.length} items in workspace:`);
      files.slice(0, 15).forEach(f => console.log(`   - ${f}`));
      if (files.length > 15) console.log(`   ... and ${files.length - 15} more`);
    }
  },
  {
    intent: 'install',
    keywords: ['install', 'add', 'get', 'fetch', 'deps', 'dependencies', 'npm', 'yarn', 'pnpm', 'bun'],
    description: 'Installs project dependencies',
    action: async () => {
      log.ai('Installing dependencies...');
      const projectType = detectProjectType();
      if (!projectType) return log.error('No project found.');
      await runCommand(projectType.manager, ['install']);
      log.success('Dependencies installed!');
    }
  }
];

// --- Helper Functions ---

function calculateLevenshteinDistance(str1, str2) {
  const matrix = [];
  for (let i = 0; i <= str2.length; i++) matrix[i] = [i];
  for (let j = 0; j <= str1.length; j++) matrix[0][j] = j;

  for (let i = 1; i <= str2.length; i++) {
    for (let j = 1; j <= str1.length; j++) {
      if (str2.charAt(i - 1) == str1.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1,
          matrix[i][j - 1] + 1,
          matrix[i - 1][j] + 1
        );
      }
    }
  }
  return matrix[str2.length][str1.length];
}

function detectProjectType() {
  const cwd = WORKSPACE_DIR;
  if (fs.existsSync(path.join(cwd, 'bun.lockb'))) return { type: 'Bun', manager: 'bun' };
  if (fs.existsSync(path.join(cwd, 'pnpm-lock.yaml'))) return { type: 'pnpm', manager: 'pnpm' };
  if (fs.existsSync(path.join(cwd, 'yarn.lock'))) return { type: 'Yarn', manager: 'yarn' };
  if (fs.existsSync(path.join(cwd, 'package-lock.json'))) return { type: 'npm', manager: 'npm' };
  if (fs.existsSync(path.join(cwd, 'package.json'))) return { type: 'npm', manager: 'npm' };
  return null;
}

function hasScript(projectType, scriptName) {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(WORKSPACE_DIR, 'package.json'), 'utf8'));
    return pkg.scripts && pkg.scripts[scriptName];
  } catch {
    return false;
  }
}

function detectDefaultScript(projectType) {
  if (hasScript(projectType, 'dev')) return 'dev';
  if (hasScript(projectType, 'start')) return 'start';
  return 'start';
}

function runCommand(cmd, args) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { stdio: 'inherit', shell: true });
    child.on('close', (code) => resolve(code));
  });
}

function findBestIntent(inputWords) {
  const inputStr = inputWords.join(' ').toLowerCase();

  // Priority 1: Check for specific patterns first (like "folder", "named", "called")
  const createPatterns = [/folder/, /directory/, /named/, /called/];
  if (createPatterns.some(p => p.test(inputStr))) {
    return INTENT_MAP.find(i => i.intent === 'create');
  }

  // Priority 2: Direct keyword match
  for (const item of INTENT_MAP) {
    if (item.keywords.some(k => inputStr.includes(k))) {
      return item;
    }
  }

  // Priority 3: Fuzzy match on individual words
  let bestMatch = null;
  let minDistance = Infinity;

  for (const word of inputWords) {
    for (const item of INTENT_MAP) {
      for (const key of item.keywords) {
        const dist = calculateLevenshteinDistance(word, key);
        if (dist <= TYPO_THRESHOLD && dist < minDistance) {
          minDistance = dist;
          bestMatch = item;
        }
      }
    }
  }

  return bestMatch;
}

async function executeIntent(intent, args) {
  console.log(`\n${colors.blue}${colors.bright}🤖 Shelly understood: "${intent.intent}"${colors.reset}\n`);
  try {
    await intent.action(args);
  } catch (error) {
    log.error(`Error executing ${intent.intent}: ${error.message}`);
  }
}

// --- Main Entry Point ---
async function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('help') || args.includes('--help') || args.includes('-h')) {
    console.log(`
${colors.cyan}${colors.bright}🐚 Shelly v2.0 - The AI-Powered CLI${colors.reset}

${colors.yellow}Usage:${colors.reset} shelly [natural language command]

${colors.yellow}Examples:${colors.reset}
  shelly start the app
  shelly create a file named test.js
  shelly make a folder called src
  shelly why is my build broken
  shelly tset my app ${colors.dim}(typo support!)${colors.reset}
  shelly clean this mess
  shelly scan my project

${colors.yellow}Commands supported:${colors.reset}
${INTENT_MAP.map(i => `  ${colors.green}•${colors.reset} ${i.intent}: ${i.description}`).join('\n')}

${colors.dim}⭐ If you like Shelly, please star us on GitHub!${colors.reset}
    `);
    return;
  }

  const intent = findBestIntent(args);

  if (intent) {
    await executeIntent(intent, args);
  } else {
    log.error('I\'m not sure what you want. Try being more specific, like:');
    console.log('   "shelly start the app"');
    console.log('   "shelly create a file named hello.js"');
    console.log('   "shelly test my code"');
  }
}

main();
